package com.vitamindispenser.backend.domain.schedule;


import com.vitamindispenser.backend.dto.schedule.DispenseEvent;
import com.vitamindispenser.backend.dto.schedule.DaySchedule;
import com.vitamindispenser.backend.dto.schedule.ScheduleRequest;
import com.vitamindispenser.backend.dto.schedule.VitaminSchedule;
import com.vitamindispenser.backend.repository.ScheduleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


import java.util.ArrayList;
import java.util.List;

@Service
public class SchedulingService {

    private final ScheduleRepository scheduleRepository;

    @Autowired
    public SchedulingService(ScheduleRepository scheduleRepository) {
        this.scheduleRepository = scheduleRepository;
    }

    /**
     * Saves a schedule request by flattening the nested structure into individual DispenseEvents
     * @param request The schedule request from the mobile app
     */
    public void saveSchedule(ScheduleRequest request) {
        List<DispenseEvent> events = new ArrayList<>();

        // Flatten the nested structure into individual DispenseEvents
        for (VitaminSchedule vitamin : request.getVitamins()) {
            String vitaminType = vitamin.getVitaminType();
            int numberOfPills = vitamin.getNumberOfPills();

            for (DaySchedule daySchedule : vitamin.getSchedule()) {
                String day = daySchedule.getDay();

                for (String time : daySchedule.getTimes()) {
                    // Create a DispenseEvent for each time slot
                    // ID will be generated by the repository
                    DispenseEvent event = new DispenseEvent(
                            numberOfPills,
                            vitaminType,
                            day,
                            time,
                            null    // id will be set by repository
                    );
                    events.add(event);
                }
            }
        }
        scheduleRepository.saveAll(events);
    }
}


